replicaCount: 3
image:
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8000
  targetPort: 8000
ingress:
  enabled: false
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80