apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secret
                  key: DJANGO_SECRET_KEY
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secret
                  key: DATABASE_NAME
          volumeMounts:
            - name: sqlite-storage
              mountPath: /app/db.sqlite3
              subPath: db.sqlite3
      volumes:
        - name: sqlite-storage
          emptyDir: {}