apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: Opaque
data:
  DJANGO_SECRET_KEY: {{ .Values.env.DJANGO_SECRET_KEY | b64enc | quote }}
  DATABASE_NAME: {{ .Values.env.DATABASE_URL | b64enc | quote }}